import argparse
import time
import sys
# Force UTF-8 encoding on standard streams to prevent charmap errors on Windows
if sys.platform.startswith('win'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except AttributeError:
        pass
import json
from pathlib import Path
from typing import List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Ensure project root is in path
ROOT = Path(__file__).parent
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from env_loader import load_lab_env
from providers import make_provider
from tools import load_tool_declarations, to_openai_tools
from datetime import datetime
from versioning import build_artifact_version, artifact_version_dict
from chat import run_model_tool_loop

# Load environment variables
load_lab_env(ROOT)

# Schema definitions matching the expected frontend schema
class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of the sender: 'system', 'user', or 'assistant'")
    content: str = Field(..., description="The textual content of the message")

class ChatRequest(BaseModel):
    messages: List[ChatMessage] = Field(..., description="The conversation history")
    temperature: Optional[float] = Field(0.0, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: Optional[int] = Field(None, gt=0, description="Maximum number of tokens to generate")
    session_id: Optional[str] = Field(None, description="The session ID from the frontend to group transcripts")

class ChatResponseUsage(BaseModel):
    prompt_tokens: int = Field(0, description="Number of tokens in the prompt")
    completion_tokens: int = Field(0, description="Number of tokens in the completion")
    total_tokens: int = Field(0, description="Total number of tokens used")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response generated by the assistant")
    model: str = Field(..., description="The model name that generated the response")
    usage: ChatResponseUsage = Field(..., description="Token usage details")
    latency_ms: float = Field(..., description="Total processing time in milliseconds")

# Simple token counting helpers
def estimate_tokens(text: str) -> int:
    if not text:
        return 0
    # Rough fallback estimate: ~4 characters per token
    return max(1, len(text) // 4)

# FastAPI App setup
app = FastAPI(
    title="Research Agent Backend MVP",
    description="FastAPI Backend for the Prompt Engineering & Tool Calling Research Agent.",
    version="1.0.0"
)

# CORS middleware for Next.js frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global variables initialized on startup
import os
import signal
import logging
import redis
from collections import deque
from fastapi import Request, Depends, Security
from fastapi.security import APIKeyHeader

PROVIDER_NAME = os.environ.get("PROVIDER_NAME", "openrouter")
VERSION_LABEL = os.environ.get("VERSION_LABEL", "v3")
MODEL_NAME = os.environ.get("MODEL_NAME", None)

# Structured JSON logging
logging.basicConfig(
    level=logging.INFO,
    format='{"ts":"%(asctime)s","lvl":"%(levelname)s","msg":"%(message)s"}',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("server")

# Redis connection
REDIS_URL = os.environ.get("REDIS_URL", "")
_redis = None
if REDIS_URL:
    try:
        _redis = redis.from_url(REDIS_URL, decode_responses=True)
        _redis.ping()
        logger.info("Connected to Redis successfully.")
    except Exception as e:
        logger.error(f"Failed to connect to Redis at {REDIS_URL}: {e}")
        _redis = None

# Graceful shutdown setup
_is_ready = True

def handle_sigterm(signum, frame):
    global _is_ready
    _is_ready = False
    logger.info("Received SIGTERM — initiating graceful shutdown...")
    time.sleep(2)
    sys.exit(0)

signal.signal(signal.SIGTERM, handle_sigterm)

# Security and Auth
api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)

async def verify_api_key(x_api_key: str = Security(api_key_header)):
    agent_api_key = os.environ.get("AGENT_API_KEY", "dev-key-change-me")
    if not x_api_key or x_api_key != agent_api_key:
        raise HTTPException(
            status_code=401,
            detail="Invalid or missing API key. Include header: X-API-Key: <key>"
        )
    return x_api_key

# Rate Limiter (Redis with in-memory fallback)
_in_memory_rate_windows = {}

def check_rate_limit(client_id: str):
    rate_limit = int(os.environ.get("RATE_LIMIT_PER_MINUTE", "10"))
    window_seconds = 60
    now = time.time()
    
    if _redis:
        key = f"rate_limit:{client_id}"
        pipe = _redis.pipeline()
        pipe.zremrangebyscore(key, 0, now - window_seconds)
        pipe.zcard(key)
        pipe.zadd(key, {str(now): now})
        pipe.expire(key, window_seconds + 5)
        _, count, _, _ = pipe.execute()
        if count >= rate_limit:
            raise HTTPException(
                status_code=429,
                detail=f"Rate limit exceeded: {rate_limit} req/min. Please try again later."
            )
    else:
        if client_id not in _in_memory_rate_windows:
            _in_memory_rate_windows[client_id] = deque()
        window = _in_memory_rate_windows[client_id]
        while window and window[0] < now - window_seconds:
            window.popleft()
        if len(window) >= rate_limit:
            raise HTTPException(
                status_code=429,
                detail=f"Rate limit exceeded: {rate_limit} req/min. Please try again later."
            )
        window.append(now)

# Cost Guard (Redis with in-memory fallback)
_in_memory_daily_cost = 0.0
_in_memory_cost_reset_day = time.strftime("%Y-%m-%d")

def check_cost_budget(client_id: str, estimated_input_tokens: int):
    global _in_memory_daily_cost, _in_memory_cost_reset_day
    daily_budget = float(os.environ.get("DAILY_BUDGET_USD", "5.0"))
    today = time.strftime("%Y-%m-%d")
    
    estimated_cost = (estimated_input_tokens / 1000) * 0.00015
    
    if _redis:
        key = f"cost_budget:{client_id}:{today}"
        current_cost = float(_redis.get(key) or 0.0)
        if current_cost + estimated_cost > daily_budget:
            raise HTTPException(
                status_code=503,
                detail="Daily token budget exhausted. Please try again tomorrow."
            )
    else:
        if today != _in_memory_cost_reset_day:
            _in_memory_daily_cost = 0.0
            _in_memory_cost_reset_day = today
        if _in_memory_daily_cost + estimated_cost > daily_budget:
            raise HTTPException(
                status_code=503,
                detail="Daily token budget exhausted. Please try again tomorrow."
            )
            
def record_actual_cost(client_id: str, input_tokens: int, output_tokens: int):
    global _in_memory_daily_cost, _in_memory_cost_reset_day
    today = time.strftime("%Y-%m-%d")
    cost = (input_tokens / 1000) * 0.00015 + (output_tokens / 1000) * 0.0006
    
    if _redis:
        key = f"cost_budget:{client_id}:{today}"
        _redis.incrbyfloat(key, cost)
        _redis.expire(key, 86400 * 2)
    else:
        if today != _in_memory_cost_reset_day:
            _in_memory_daily_cost = 0.0
            _in_memory_cost_reset_day = today
        _in_memory_daily_cost += cost

@app.get("/")
async def root():
    return {
        "status": "online",
        "message": "Research Agent Backend MVP is running."
    }

@app.get("/health")
async def health_check():
    return {"status": "ok"}

@app.get("/ready")
async def readiness_check():
    if not _is_ready:
        raise HTTPException(status_code=503, detail="Agent is shutting down")
    if _redis:
        try:
            _redis.ping()
        except Exception as e:
            raise HTTPException(status_code=503, detail=f"Redis connection failed: {e}")
    return {"ready": True}

@app.get("/api/health")
async def health():
    return {
        "status": "healthy",
        "provider": PROVIDER_NAME,
        "version": VERSION_LABEL,
        "model": MODEL_NAME or "default",
        "openai_base_url": os.environ.get("OPENAI_BASE_URL"),
        "local_llm_tunnel_url": os.environ.get("LOCAL_LLM_TUNNEL_URL")
    }

# ── Log Viewer API ───────────────────────────────────────────
RUNS_DIR = ROOT / "runs"
TRANSCRIPTS_DIR = ROOT / "transcripts"
SAMPLES_RUNS_DIR = ROOT / "samples" / "runs"
SAMPLES_TRANSCRIPTS_DIR = ROOT / "samples" / "transcripts"

@app.get("/api/logs/runs")
async def list_runs(x_api_key: str = Depends(verify_api_key)):
    """Return summary metadata for every eval-run JSON."""
    items = []
    for d in [RUNS_DIR, SAMPLES_RUNS_DIR]:
        if not d.exists():
            continue
        for f in sorted(d.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                items.append({
                    "file": str(f.relative_to(ROOT)),
                    "run_id": data.get("run_id", f.stem),
                    "version": data.get("version"),
                    "artifact_version": data.get("artifact_version"),
                    "suite": data.get("suite"),
                    "provider": data.get("provider"),
                    "model": data.get("model"),
                    "generated_at": data.get("generated_at"),
                    "summary": data.get("summary", {}),
                })
            except Exception:
                continue
    return {"runs": items}

@app.get("/api/logs/transcripts")
async def list_transcripts(x_api_key: str = Depends(verify_api_key)):
    """Return summary metadata for every transcript JSON."""
    items = []
    for d in [TRANSCRIPTS_DIR, SAMPLES_TRANSCRIPTS_DIR]:
        if not d.exists():
            continue
        for f in sorted(d.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                items.append({
                    "file": str(f.relative_to(ROOT)),
                    "transcript_id": data.get("transcript_id", f.stem),
                    "version": data.get("version"),
                    "provider": data.get("provider"),
                    "model": data.get("model"),
                    "created_at": data.get("created_at"),
                    "turn_count": len(data.get("turns", [])),
                })
            except Exception:
                continue
    return {"transcripts": items}

@app.get("/api/logs/detail")
async def log_detail(file: str, x_api_key: str = Depends(verify_api_key)):
    """Return full content of a specific log JSON file (restricted to runs/ transcripts/ samples/)."""
    target = (ROOT / file).resolve()
    # Security: only allow reading inside the project
    if not str(target).startswith(str(ROOT.resolve())):
        raise HTTPException(status_code=403, detail="Access denied")
    if not target.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return json.loads(target.read_text(encoding="utf-8"))

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest, x_api_key: str = Depends(verify_api_key)):
    # 1. Rate Limiting
    check_rate_limit(x_api_key[:8])
    
    # 2. Token cost estimation and check
    input_text = " ".join([m.content for m in request.messages])
    prompt_tokens = estimate_tokens(input_text)
    check_cost_budget(x_api_key[:8], prompt_tokens)
    
    start_time = time.time()
    
    logger.info(json.dumps({
        "event": "agent_call_start",
        "session_id": request.session_id,
        "input_len": len(input_text),
        "prompt_tokens": prompt_tokens
    }))
    
    try:
        # 1. Load prompts and tools dynamically to reflect modifications immediately
        system_prompt_path = ROOT / "artifacts" / "system_prompt.md"
        tools_path = ROOT / "artifacts" / "tools.yaml"
        
        system_prompt = system_prompt_path.read_text(encoding="utf-8")
        tool_declarations = load_tool_declarations(tools_path)
        openai_tools = to_openai_tools(tool_declarations)
        
        # 2. Build provider
        provider = make_provider(PROVIDER_NAME)
        selected_model = MODEL_NAME or getattr(provider, "default_model", None)
        
        # 3. Format history for agent
        formatted_messages = [
            {"role": msg.role, "content": msg.content} 
            for msg in request.messages
        ]
        
        # If system message is not present in formatted_messages, inject it
        has_system = any(m["role"] == "system" for m in formatted_messages)
        if not has_system:
            formatted_messages = [{"role": "system", "content": system_prompt}] + formatted_messages
            
        # 4. Execute the agent tool loop
        result = run_model_tool_loop(
            provider=provider,
            messages=formatted_messages,
            tools=openai_tools,
            model=selected_model,
            max_tool_rounds=4
        )
        reply = result.get("assistant_text", "")
        
        # 5. Measure latency and calculate tokens
        end_time = time.time()
        latency_ms = (end_time - start_time) * 1000
        
        completion_tokens = estimate_tokens(reply)
        total_tokens = prompt_tokens + completion_tokens
        
        # Record actual cost
        record_actual_cost(x_api_key[:8], prompt_tokens, completion_tokens)
        
        logger.info(json.dumps({
            "event": "agent_call_success",
            "session_id": request.session_id,
            "status": result.get("status", "answered"),
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens,
            "latency_ms": round(latency_ms, 2)
        }))
        
        # 6. Save transcript if session_id is provided
        if request.session_id:
            try:
                def now_iso() -> str:
                    return datetime.now().isoformat(timespec="seconds")
                
                TRANSCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
                transcript_path = TRANSCRIPTS_DIR / f"web_{request.session_id}.json"
                
                transcript = None
                if transcript_path.exists():
                    try:
                        transcript = json.loads(transcript_path.read_text(encoding="utf-8"))
                    except Exception:
                        pass
                
                if not transcript:
                    artifact_version = build_artifact_version(VERSION_LABEL, system_prompt_path, tools_path)
                    transcript = {
                        "transcript_id": f"web_{request.session_id}",
                        **artifact_version_dict(artifact_version),
                        "provider": PROVIDER_NAME,
                        "model": selected_model or PROVIDER_NAME,
                        "system_prompt": str(system_prompt_path),
                        "tools": str(tools_path),
                        "history_window": 5,
                        "max_tool_rounds": 4,
                        "created_at": now_iso(),
                        "turns": []
                    }
                
                user_text = request.messages[-1].content if request.messages else ""
                turn_index = len(transcript.get("turns", [])) + 1
                
                turn_record = {
                    "turn_index": turn_index,
                    "started_at": now_iso(),
                    "user": user_text,
                    "status": result.get("status", "answered"),
                    "assistant_text": reply,
                    "rounds": result.get("rounds", []),
                    "tool_events": result.get("tool_events", []),
                    "ended_at": now_iso(),
                    "latency_ms": latency_ms,
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "total_tokens": total_tokens
                }
                
                transcript["turns"].append(turn_record)
                transcript["updated_at"] = now_iso()
                
                transcript_path.write_text(json.dumps(transcript, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
                logger.info(f"Saved web transcript to {transcript_path}")
            except Exception as e:
                logger.error(f"Error writing transcript: {e}")
        
        return ChatResponse(
            reply=reply,
            model=selected_model or PROVIDER_NAME,
            usage=ChatResponseUsage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=total_tokens
            ),
            latency_ms=latency_ms
        )
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

def main():
    global PROVIDER_NAME, VERSION_LABEL, MODEL_NAME
    
    parser = argparse.ArgumentParser(description="FastAPI Backend for Research Agent.")
    parser.add_argument("--provider", choices=["openrouter", "openai", "anthropic", "gemini"], default="openrouter")
    parser.add_argument("--model", default=None)
    parser.add_argument("--version", default="v3", help="Student-chosen artifact version label, e.g. v3.")
    parser.add_argument("--host", default="0.0.0.0", help="Host to bind the server to.")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    
    import os
    PROVIDER_NAME = os.environ.get("PROVIDER_NAME") or args.provider
    VERSION_LABEL = os.environ.get("VERSION_LABEL") or args.version
    MODEL_NAME = args.model or os.environ.get("MODEL_NAME")
    
    # Read host and port from environment variables dynamically (vital for Railway)
    host = os.environ.get("HOST") or args.host
    port_str = os.environ.get("PORT")
    port = int(port_str) if port_str else args.port
    
    print(f"Starting Research Agent Server on {host}:{port}...")
    print(f"Provider: {PROVIDER_NAME}, Version: {VERSION_LABEL}, Model: {MODEL_NAME or 'default'}")
    
    uvicorn.run("app.main:app", host=host, port=port, reload=False)

if __name__ == "__main__":
    main()
